### PR TITLE
Initial implementation of permission denied debugging.

### PR DESCRIPTION
**Pull request by pkaminski**
This change is [Reviewable](https://reviewable.io/reviews/pkaminski/firefight/1)

### CODE REVIEW

**Review by pkaminski — COMMENTED** [review]
Hey +reviewer:@jwngr, this is my first cut at redoing the permission denied debugger -- could you please take a look?  Completely untested code so far so a casual look at the overall shape is sufficient.  I also left some questions inline.  Thanks!  Update to NodeFire will follow shortly.

> *[Reviewable](https://reviewable.io/reviews/pkaminski/firefight/1#-:-LO1VGaW1UDtRiLmbENq:b-i09cj4)* status: 0 of 6 files reviewed, 3 unresolved discussions

___
*[firefight.js, line 57 at r1](https://reviewable.io/reviews/pkaminski/firefight/1#-LO1VwrUBaPVi5Y6wrNf:-LO1VwrUBaPVi5Y6wrNg:b-pomfqf) ([raw file](https://github.com/pkaminski/firefight/blob/9c58baa329b3dfafb02504a87599af98411aaafb/firefight.js#L57)):*
> ```JavaScript
>       new Firebase(database.ref().toString(), 'permission_denied_simulator');
>     this._databaseUrl = this._simulatedFirebase.toString();
>     this._tokenGenerator = new FirebaseTokenGenerator(legacySecret);
> ```

Do I understand correctly that the only way to generate `simulate`/`debug` tokens for the 2.x SDK is with a legacy secret, rather than a modern OAuth2 token?
___
*[firefight.js, line 66 at r1](https://reviewable.io/reviews/pkaminski/firefight/1#-LO1WNvh1nVUk3HMeRCF:-LO1WNvh1nVUk3HMeRCG:b-8510q) ([raw file](https://github.com/pkaminski/firefight/blob/9c58baa329b3dfafb02504a87599af98411aaafb/firefight.js#L66)):*
> ```JavaScript
>    */
>   isPermissionDenied(error) {
>     const code = error.code || error.message;
> ```

Is the structure of the errors thrown by the new SDKs documented somewhere?  I couldn't find it.
___
*[firefight.js, line 104 at r1](https://reviewable.io/reviews/pkaminski/firefight/1#-LO1Wun73ax5ZVch2Z3x:-LO1Wun73ax5ZVch2Z3y:b-dvbs4) ([raw file](https://github.com/pkaminski/firefight/blob/9c58baa329b3dfafb02504a87599af98411aaafb/firefight.js#L104)):*
> ```JavaScript
>     simulationQueue = simulationQueue
>       .catch(() => {/* ignore errors from previous simulations */})
>       .then(() => this._simulateCalls(token, simulatedRef, calls));
> ```

If you have experience with async/await, can you think of a way to construct a promise queue to serialize operations using just those?  Basically we must make sure that only one debugging operation is in progress at any given time, otherwise we won't know how to attribute the console output.  I failed to come up with anything, so falling back on raw promises here.

**Review by jwngr — CHANGES_REQUESTED** [review]
Overall this looks great and is nice and clean. I also quite like the name :) Left a few comments for you to consider.

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firefight/1#-:-LO7j1ZSCH91GqmJjJf0:buo31n3)* status: all files reviewed, 3 unresolved discussions (waiting on @pkaminski)

___
*[firefight.js, line 57 at r1](https://reviewable.io/reviews/pkaminski/firefight/1#-LO1VwrUBaPVi5Y6wrNf:-LO7ehbnEVnm152BeiNl:b-87rmoq) ([raw file](https://github.com/pkaminski/firefight/blob/9c58baa329b3dfafb02504a87599af98411aaafb/firefight.js#L57)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Do I understand correctly that the only way to generate `simulate`/`debug` tokens for the 2.x SDK is with a legacy secret, rather than a modern OAuth2 token?
</blockquote></details>

That is correct.
___
*[firefight.js, line 66 at r1](https://reviewable.io/reviews/pkaminski/firefight/1#-LO1WNvh1nVUk3HMeRCF:-LO7en7-0sB4FbeJQARg:b7mmkdx) ([raw file](https://github.com/pkaminski/firefight/blob/9c58baa329b3dfafb02504a87599af98411aaafb/firefight.js#L66)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Is the structure of the errors thrown by the new SDKs documented somewhere?  I couldn't find it.
</blockquote></details>

This logic is correct for the new SDKs as well. Error codes / messages for the Realtime Database did not change, although most other services changed to error objects with [this format](https://firebase.google.com/docs/reference/node/firebase.FirebaseError).
___
*[firefight.js, line 104 at r1](https://reviewable.io/reviews/pkaminski/firefight/1#-LO1Wun73ax5ZVch2Z3x:-LO7gvLx4XMu6HLLaMHd:bxwo8t1) ([raw file](https://github.com/pkaminski/firefight/blob/9c58baa329b3dfafb02504a87599af98411aaafb/firefight.js#L104)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

If you have experience with async/await, can you think of a way to construct a promise queue to serialize operations using just those?  Basically we must make sure that only one debugging operation is in progress at any given time, otherwise we won't know how to attribute the console output.  I failed to come up with anything, so falling back on raw promises here.
</blockquote></details>

No, I can't think of how to do that with async / await either. This logic with raw promises looks correct though.
___
*[firefight.js, line 101 at r2](https://reviewable.io/reviews/pkaminski/firefight/1#-LO7iBx55iyRQP-LgnQq:-LO7iBx55iyRQP-LgnQr:by8suim) ([raw file](https://github.com/pkaminski/firefight/blob/86b47fe3004db32110ab1c9dcb924d0ccf9efd98/firefight.js#L101)):*
> ```JavaScript
>     // Intercept the console as late as possible, so that we can add our filter at the top and elide
>     // permission traces before anybody else tries to process them.
>     interceptConsoleLog();
> ```

After the queue empties, should we "un-intercept" `console.log()`?
___
*[firefight.js, line 112 at r2](https://reviewable.io/reviews/pkaminski/firefight/1#-LO7hMkz0asFTu9Pd1PC:-LO7hMkz0asFTu9Pd1PD:bdtweao) ([raw file](https://github.com/pkaminski/firefight/blob/86b47fe3004db32110ab1c9dcb924d0ccf9efd98/firefight.js#L112)):*
> ```JavaScript
>       this._simulatedFirebase.unauth();
>       await this._simulatedFirebase.authWithCustomToken(
>         token, () => {/* ignore */}, {remember: 'none'});
> ```

Don't you want to move all the call below into the `onComplete()` instead of outside of it? In practice, it likely won't matter since `authWithCustomToken()` has no network component and will run synchronously and this library will never be updated again to change this method, but it is more correct to move that stuff into the `onComplete()`.
___
*[firefight.js, line 118 at r2](https://reviewable.io/reviews/pkaminski/firefight/1#-LO7hgn57f0vL8OO37Ws:-LO7hgn57f0vL8OO37Wt:b-vo7got) ([raw file](https://github.com/pkaminski/firefight/blob/86b47fe3004db32110ab1c9dcb924d0ccf9efd98/firefight.js#L118)):*
> ```JavaScript
>         if (trace) traces.push(trace);
>       }
>       if (!traces.lenth) return 'Unable to reproduce error in simulation';
> ```

Typo: `traces.length`.

**Review by pkaminski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firefight/1)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @jwngr and @pkaminski)

___
*[firefight.js, line 101 at r2](https://reviewable.io/reviews/pkaminski/firefight/1#-LO7iBx55iyRQP-LgnQq:-LOC9eZ07EupPJA39ghv:bgzfbiy) ([raw file](https://github.com/pkaminski/firefight/blob/86b47fe3004db32110ab1c9dcb924d0ccf9efd98/firefight.js#L101)):*
<details><summary><i>Previously, jwngr (Jacob Wenger) wrote…</i></summary><blockquote>

After the queue empties, should we "un-intercept" `console.log()`?
</blockquote></details>

The first rule of monkey-patching is: never undo a monkey-patch!  (If somebody else put a patch on top of yours, you'd also be undoing theirs.  Unless you check whether the current function is still the one you patched in, and leave things be if it doesn't match...  But then you have to plan for leaving the patch in anyway, so might as well just let it be.)
___
*[firefight.js, line 112 at r2](https://reviewable.io/reviews/pkaminski/firefight/1#-LO7hMkz0asFTu9Pd1PC:-LOCA6pz9NfR_G1fKWL4:b-cqqchj) ([raw file](https://github.com/pkaminski/firefight/blob/86b47fe3004db32110ab1c9dcb924d0ccf9efd98/firefight.js#L112)):*
<details><summary><i>Previously, jwngr (Jacob Wenger) wrote…</i></summary><blockquote>

Don't you want to move all the call below into the `onComplete()` instead of outside of it? In practice, it likely won't matter since `authWithCustomToken()` has no network component and will run synchronously and this library will never be updated again to change this method, but it is more correct to move that stuff into the `onComplete()`.
</blockquote></details>

That's what the `await` is for.  :)  The blank `onComplete` is needed just so I can pass the options argument.
___
*[firefight.js, line 118 at r2](https://reviewable.io/reviews/pkaminski/firefight/1#-LO7hgn57f0vL8OO37Ws:-LOCAKsQAuwIjc7nMlm8:b-896fix) ([raw file](https://github.com/pkaminski/firefight/blob/86b47fe3004db32110ab1c9dcb924d0ccf9efd98/firefight.js#L118)):*
<details><summary><i>Previously, jwngr (Jacob Wenger) wrote…</i></summary><blockquote>

Typo: `traces.length`.
</blockquote></details>

Done.

**Review by jwngr — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firefight/1#-:-LOD64xd5Z9U53UbjLYh:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @jwngr and @pkaminski)

___
*[firefight.js, line 101 at r2](https://reviewable.io/reviews/pkaminski/firefight/1#-LO7iBx55iyRQP-LgnQq:-LOD5HFb-HFOxyUfYGvv:b-aydv6k) ([raw file](https://github.com/pkaminski/firefight/blob/86b47fe3004db32110ab1c9dcb924d0ccf9efd98/firefight.js#L101)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

The first rule of monkey-patching is: never undo a monkey-patch!  (If somebody else put a patch on top of yours, you'd also be undoing theirs.  Unless you check whether the current function is still the one you patched in, and leave things be if it doesn't match...  But then you have to plan for leaving the patch in anyway, so might as well just let it be.)
</blockquote></details>

Haha that makes a lot of sense. Seems like a lesson you may have learned the hard way :)
___
*[firefight.js, line 112 at r2](https://reviewable.io/reviews/pkaminski/firefight/1#-LO7hMkz0asFTu9Pd1PC:-LOD5X3E1D51xyvAevGw:b-9ko7cj) ([raw file](https://github.com/pkaminski/firefight/blob/86b47fe3004db32110ab1c9dcb924d0ccf9efd98/firefight.js#L112)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

That's what the `await` is for.  :)  The blank `onComplete` is needed just so I can pass the options argument.
</blockquote></details>

Yikes, yeah. Okay, ignore me.
___
*[firefight.js, line 93 at r3](https://reviewable.io/reviews/pkaminski/firefight/1#-LOD5iSCBMgSTp_3HwHg:-LOD5iSCBMgSTp_3HwHh:b-u6i9um) ([raw file](https://github.com/pkaminski/firefight/blob/3a4d73e53e4801ebb9fe8613545376f76d1d5a04/firefight.js#L93)):*
> ```JavaScript
>   }
> 
>   async _simulate(token, ref, calls) {
> ```

Nit: this is a public method (you use it in the `SimulatorProxy` class above), so you should probably drop the `_` prefix.

**Review by pkaminski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firefight/1)* status: all files reviewed, 1 unresolved discussion (waiting on @jwngr)

___
*[firefight.js, line 93 at r3](https://reviewable.io/reviews/pkaminski/firefight/1#-LOD5iSCBMgSTp_3HwHg:-LOE_QmQ0OIxHLtOX7YM:bvn2gp) ([raw file](https://github.com/pkaminski/firefight/blob/3a4d73e53e4801ebb9fe8613545376f76d1d5a04/firefight.js#L93)):*
<details><summary><i>Previously, jwngr (Jacob Wenger) wrote…</i></summary><blockquote>

Nit: this is a public method (you use it in the `SimulatorProxy` class above), so you should probably drop the `_` prefix.
</blockquote></details>

Normally I subscribe to the strict-private semantics you propose, but when i) the method is on an instance exposed via the public API, ii) fixing would require deep and otherwise unnecessary structural changes, and iii) the accessing entity is a "helper" that would be defined nested inside the host class if the language allowed it, I'm willing to make an exception.

**Pull request merged**
